openapi: 3.0.3
info:
  version: 1.0.0
  title: test type mappings
components:
  schemas:
    TestCreate:
      type: object
      properties:
        features:
          type: array
          items:
            type: Feature
paths:
  /v1/test:
    get:
      responses:
        '200':
          description: test

